---
nxos-test:
  nornir_host: 172.16.1.54
  groups: ['default', 'Group1']

arista-test:
  nornir_host: 192.168.1.57
  groups: ['default', 'Group2']

juniper-test:
  nornir_host: 192.168.1.39
  groups: ['default', 'Group3']
